document.write("\
<h1 align=left>Schaakclub Dordrecht</h1>\
<h2 align=left>Pairing round: 1</h2>\
<br>\
<table border='0'>\
<tr><td width='4%' align='left'>&nbsp;</td><td width='28%' align='left'><h2>Inter club competition</h2></td><td width='4%' align='center'>+</td><td width='12%' align='center'>Results</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'>1 </td><td width='28%' align='left'>Heeren, A. van (Arie )</td><td width='4%' align='center'>10</td><td width='12%' align='center'>Inter club</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
</table>\
<br />\
<br />\
<h2>Championship games</h2>\
<br />\
<table border='0'>\
<tr><td width='4%' align='left'>&nbsp;</td><td width='28%' align='left'>Player white</td><td width='4%' align='center'>+</td><td width='4%' align='center'>+/-</td><td width='4%' align='center'>-</td><td width='4%' align='center'>against</td><td width='28%' align='left'>Player black</td><td width='4%' align='center'>+</td><td width='4%' align='center'>+/-</td><td width='4%' align='center'>-</td><td width='12%' align='center'>Results</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'>2 </td><td width='28%' align='left'>Wilde, R. de (Rik )</td><td width='4%' align='center'>20,0</td><td width='4%' align='center'>-10,0</td><td width='4%' align='center'>-40,0</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Eikelboom, B.  (Berend )</td><td width='4%' align='center'>40,0</td><td width='4%' align='center'>10,0</td><td width='4%' align='center'>-20,0</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'>3 </td><td width='28%' align='left'>Boer, L. den (Lennard )</td><td width='4%' align='center'>20,0</td><td width='4%' align='center'>-10,0</td><td width='4%' align='center'>-40,0</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Apon, H.  (Iwahn )</td><td width='4%' align='center'>40,0</td><td width='4%' align='center'>10,0</td><td width='4%' align='center'>-20,0</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
</table>\
<br />\
<br />\
<h2>Clubcompetition</h2>\
<table border='0'>\
<br />\
<tr><td width='4%' align='left'>&nbsp;</td><td width='28%' align='left'>Player white</td><td width='4%' align='center'>+</td><td width='4%' align='center'>+/-</td><td width='4%' align='center'>-</td><td width='4%' align='center'>against</td><td width='28%' align='left'>Player black</td><td width='4%' align='center'>+</td><td width='4%' align='center'>+/-</td><td width='4%' align='center'>-</td><td width='12%' align='center'>Results</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2802&Player2=2793'>4</a> </td><td width='28%' align='left'>Timmermans, A.L.  (Adri )</td><td width='4%' align='center'>40,0</td><td width='4%' align='center'>10,0</td><td width='4%' align='center'>-20,0</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Pluymert, P.W.  (Piet )</td><td width='4%' align='center'>20,0</td><td width='4%' align='center'>-10,0</td><td width='4%' align='center'>-40,0</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2808&Player2=2767'>5</a> </td><td width='28%' align='left'>Vogelesang, S  (Sander )</td><td width='4%' align='center'>40,0</td><td width='4%' align='center'>10,0</td><td width='4%' align='center'>-20,0</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Hennekes, J.  (Jacques )</td><td width='4%' align='center'>20,0</td><td width='4%' align='center'>-10,0</td><td width='4%' align='center'>-40,0</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2799&Player2=2745'>6</a> </td><td width='28%' align='left'>Sitton, B.  (Ben )</td><td width='4%' align='center'>40,0</td><td width='4%' align='center'>10,0</td><td width='4%' align='center'>-20,0</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Abee, K.  (Koos )</td><td width='4%' align='center'>20,0</td><td width='4%' align='center'>-10,0</td><td width='4%' align='center'>-40,0</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2794&Player2=2757'>7</a> </td><td width='28%' align='left'>Pluymert, M.  (Marcel )</td><td width='4%' align='center'>21,3</td><td width='4%' align='center'>-8,7</td><td width='4%' align='center'>-38,7</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Dwars, C.  (Conchita )</td><td width='4%' align='center'>38,7</td><td width='4%' align='center'>8,7</td><td width='4%' align='center'>-21,3</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2749&Player2=2806'>8</a> </td><td width='28%' align='left'>Blommestein, V. van (Victor )</td><td width='4%' align='center'>31,3</td><td width='4%' align='center'>1,3</td><td width='4%' align='center'>-28,7</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Versloot, J.W.  (Jan Willem )</td><td width='4%' align='center'>28,7</td><td width='4%' align='center'>-1,3</td><td width='4%' align='center'>-31,3</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2760&Player2=2779'>9</a> </td><td width='28%' align='left'>Griend, J. van de (Johan )</td><td width='4%' align='center'>26,7</td><td width='4%' align='center'>-3,3</td><td width='4%' align='center'>-33,3</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Laar, J.C. van de (John )</td><td width='4%' align='center'>33,3</td><td width='4%' align='center'>3,3</td><td width='4%' align='center'>-26,7</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2803&Player2=2763'>10</a> </td><td width='28%' align='left'>Timmermans, H.J.  (Henk )</td><td width='4%' align='center'>24,5</td><td width='4%' align='center'>-5,5</td><td width='4%' align='center'>-35,5</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Haren, O.C. van (Otto )</td><td width='4%' align='center'>35,5</td><td width='4%' align='center'>5,5</td><td width='4%' align='center'>-24,5</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2762&Player2=2754'>11</a> </td><td width='28%' align='left'>Grootheest, A. van (Arend )</td><td width='4%' align='center'>32,1</td><td width='4%' align='center'>2,1</td><td width='4%' align='center'>-27,9</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Bruin, W. de (Wouter )</td><td width='4%' align='center'>27,9</td><td width='4%' align='center'>-2,1</td><td width='4%' align='center'>-32,1</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2783&Player2=2797'>12</a> </td><td width='28%' align='left'>Maertelaere, A. de (Anton )</td><td width='4%' align='center'>30,1</td><td width='4%' align='center'>0,1</td><td width='4%' align='center'>-29,9</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Rijneveen, M.  (Martijn )</td><td width='4%' align='center'>29,9</td><td width='4%' align='center'>-0,1</td><td width='4%' align='center'>-30,1</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2816&Player2=2813'>13</a> </td><td width='28%' align='left'>Slotboom, T  (Teus )</td><td width='4%' align='center'>30,5</td><td width='4%' align='center'>0,5</td><td width='4%' align='center'>-29,5</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Wingerden, E. van (Erwin )</td><td width='4%' align='center'>29,5</td><td width='4%' align='center'>-0,5</td><td width='4%' align='center'>-30,5</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2787&Player2=2769'>14</a> </td><td width='28%' align='left'>Noort, W. van (Wim )</td><td width='4%' align='center'>31,6</td><td width='4%' align='center'>1,6</td><td width='4%' align='center'>-28,4</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Hobe, T.  (Ton )</td><td width='4%' align='center'>28,4</td><td width='4%' align='center'>-1,6</td><td width='4%' align='center'>-31,6</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2815&Player2=2798'>15</a> </td><td width='28%' align='left'>Zwartjes, G.  (Gert )</td><td width='4%' align='center'>29,0</td><td width='4%' align='center'>-1,0</td><td width='4%' align='center'>-31,0</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Schreuder, P.J.  (Hans )</td><td width='4%' align='center'>31,0</td><td width='4%' align='center'>1,0</td><td width='4%' align='center'>-29,0</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2807&Player2=2770'>16</a> </td><td width='28%' align='left'>Visser, T  (Theo )</td><td width='4%' align='center'>28,6</td><td width='4%' align='center'>-1,4</td><td width='4%' align='center'>-31,4</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Hoek, T. van (Thijs )</td><td width='4%' align='center'>31,4</td><td width='4%' align='center'>1,4</td><td width='4%' align='center'>-28,6</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2788&Player2=2773'>17</a> </td><td width='28%' align='left'>Nugteren, B.  (Bas )</td><td width='4%' align='center'>29,7</td><td width='4%' align='center'>-0,3</td><td width='4%' align='center'>-30,3</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Jelier, R.  (Rick )</td><td width='4%' align='center'>30,3</td><td width='4%' align='center'>0,3</td><td width='4%' align='center'>-29,7</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2784&Player2=2753'>18</a> </td><td width='28%' align='left'>Manen, B. van (Bert )</td><td width='4%' align='center'>31,7</td><td width='4%' align='center'>1,7</td><td width='4%' align='center'>-28,3</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Bonninga, A.  (Anko )</td><td width='4%' align='center'>28,3</td><td width='4%' align='center'>-1,7</td><td width='4%' align='center'>-31,7</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2789&Player2=2761'>19</a> </td><td width='28%' align='left'>Nugteren, D.  (Dick )</td><td width='4%' align='center'>30,9</td><td width='4%' align='center'>0,9</td><td width='4%' align='center'>-29,1</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Groot, B.D.  (Dick )</td><td width='4%' align='center'>29,1</td><td width='4%' align='center'>-0,9</td><td width='4%' align='center'>-30,9</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2785&Player2=2792'>20</a> </td><td width='28%' align='left'>Monster, H.  (Henk )</td><td width='4%' align='center'>30,1</td><td width='4%' align='center'>0,1</td><td width='4%' align='center'>-29,9</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Peters, E  (Elroy )</td><td width='4%' align='center'>29,9</td><td width='4%' align='center'>-0,1</td><td width='4%' align='center'>-30,1</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2765&Player2=2751'>21</a> </td><td width='28%' align='left'>Hauser, J.  (Johann )</td><td width='4%' align='center'>40,0</td><td width='4%' align='center'>10,0</td><td width='4%' align='center'>-20,0</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Boersma, J. A.  (Hans )</td><td width='4%' align='center'>20,0</td><td width='4%' align='center'>-10,0</td><td width='4%' align='center'>-40,0</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2759&Player2=2748'>22</a> </td><td width='28%' align='left'>Fafie, P.  (Peter )</td><td width='4%' align='center'>26,4</td><td width='4%' align='center'>-3,6</td><td width='4%' align='center'>-33,6</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Barends, H.  (Henk )</td><td width='4%' align='center'>33,6</td><td width='4%' align='center'>3,6</td><td width='4%' align='center'>-26,4</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2764&Player2=2768'>23</a> </td><td width='28%' align='left'>Harms, A.  (Aart )</td><td width='4%' align='center'>23,8</td><td width='4%' align='center'>-6,2</td><td width='4%' align='center'>-36,2</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Hertog, J.A.P. den (Johan )</td><td width='4%' align='center'>36,2</td><td width='4%' align='center'>6,2</td><td width='4%' align='center'>-23,8</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='left'><a href='http://81.204.177.61/TSGS_CS_Show_One_Game_History.aspx?Player1=2796&Player2=2776'>24</a> </td><td width='28%' align='left'>Reijenga, J.  (Jan )</td><td width='4%' align='center'>27,2</td><td width='4%' align='center'>-2,8</td><td width='4%' align='center'>-32,8</td><td width='4%' align='center'> - </td><td width='28%' align='left'>Kelholt, H.  (Henk )</td><td width='4%' align='center'>32,8</td><td width='4%' align='center'>2,8</td><td width='4%' align='center'>-27,2</td><td width='12%' align='center'>.. - ..</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
</table>\
<br />\
<br />\
");
