//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSGS_CS_Login_Client.TSGS_MLC_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TSGS_MLC_Service.ITSGS_MLC_Service")]
    public interface ITSGS_MLC_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITSGS_MLC_Service/GetMLCText", ReplyAction="http://tempuri.org/ITSGS_MLC_Service/GetMLCTextResponse")]
        string GetMLCText(string Project, string Page, int Language, int OrderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITSGS_MLC_Service/GetMLCText", ReplyAction="http://tempuri.org/ITSGS_MLC_Service/GetMLCTextResponse")]
        System.Threading.Tasks.Task<string> GetMLCTextAsync(string Project, string Page, int Language, int OrderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITSGS_MLC_Service/GetLanguageList", ReplyAction="http://tempuri.org/ITSGS_MLC_Service/GetLanguageListResponse")]
        System.Data.DataSet GetLanguageList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITSGS_MLC_Service/GetLanguageList", ReplyAction="http://tempuri.org/ITSGS_MLC_Service/GetLanguageListResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetLanguageListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITSGS_MLC_Service/TranslateLanguages", ReplyAction="http://tempuri.org/ITSGS_MLC_Service/TranslateLanguagesResponse")]
        void TranslateLanguages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITSGS_MLC_Service/TranslateLanguages", ReplyAction="http://tempuri.org/ITSGS_MLC_Service/TranslateLanguagesResponse")]
        System.Threading.Tasks.Task TranslateLanguagesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITSGS_MLC_ServiceChannel : TSGS_CS_Login_Client.TSGS_MLC_Service.ITSGS_MLC_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TSGS_MLC_ServiceClient : System.ServiceModel.ClientBase<TSGS_CS_Login_Client.TSGS_MLC_Service.ITSGS_MLC_Service>, TSGS_CS_Login_Client.TSGS_MLC_Service.ITSGS_MLC_Service {
        
        public TSGS_MLC_ServiceClient() {
        }
        
        public TSGS_MLC_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TSGS_MLC_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TSGS_MLC_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TSGS_MLC_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMLCText(string Project, string Page, int Language, int OrderNumber) {
            return base.Channel.GetMLCText(Project, Page, Language, OrderNumber);
        }
        
        public System.Threading.Tasks.Task<string> GetMLCTextAsync(string Project, string Page, int Language, int OrderNumber) {
            return base.Channel.GetMLCTextAsync(Project, Page, Language, OrderNumber);
        }
        
        public System.Data.DataSet GetLanguageList() {
            return base.Channel.GetLanguageList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetLanguageListAsync() {
            return base.Channel.GetLanguageListAsync();
        }
        
        public void TranslateLanguages() {
            base.Channel.TranslateLanguages();
        }
        
        public System.Threading.Tasks.Task TranslateLanguagesAsync() {
            return base.Channel.TranslateLanguagesAsync();
        }
    }
}
