document.write("\
<div id='printable' class='PrintSettings'>\
<h1 align=left>Schaakclub Dordrecht, Championship group overview</h1>\
<br><table border='1px'>
<tr><td align='center'>&nbsp;</td><td align='left'>Name</td><td align='center'>1</td><td align='center'>2</td><td align='center'>3</td><td align='center'>4</td><td align='center'>5</td><td align='center'>6</td><td align='center'>7</td><td align='center'>8</td><td align='center'>Total</td>
<tr><td align='center'>1</td><td align='left'>Timmermans, M.A.  (Mark)                </td><td align='center' style='background-color:grey'><img src='../images/scdlogodoorzichtig.gif' height='16' ></td><td align='center'>0,5</td><td align='center'>0,5</td><td align='center'>1</td><td align='center'>1</td><td align='center'>1</td><td align='center'>1</td><td align='center'>1</td><td align='center'>6</td></tr>
<tr><td align='center'>2</td><td align='left'>Krul, R.  (Rene)                        </td><td align='center'>0,5</td><td align='center' style='background-color:grey'><img src='../images/scdlogodoorzichtig.gif' height='16' ></td><td align='center'>0,5</td><td align='center'>1</td><td align='center'>1</td><td align='center'>1</td><td align='center'>1</td><td align='center'>0,5</td><td align='center'>5,5</td></tr>
<tr><td align='center'>3</td><td align='left'>Boer, L. den (Lennard)                  </td><td align='center'>0,5</td><td align='center'>0,5</td><td align='center' style='background-color:grey'><img src='../images/scdlogodoorzichtig.gif' height='16' ></td><td align='center'>1</td><td align='center'>0</td><td align='center'>1</td><td align='center'>0,5</td><td align='center'>1</td><td align='center'>4,5</td></tr>
<tr><td align='center'>4</td><td align='left'>Jong, J. de (Joop)                      </td><td align='center'>0</td><td align='center'>0</td><td align='center'>0</td><td align='center' style='background-color:grey'><img src='../images/scdlogodoorzichtig.gif' height='16' ></td><td align='center'>1</td><td align='center'>0</td><td align='center'>1</td><td align='center'>1</td><td align='center'>3</td></tr>
<tr><td align='center'>&nbsp;</td><td align='left'>Wilde, R. de (Rik)                      </td><td align='center'>0</td><td align='center'>0</td><td align='center'>1</td><td align='center'>0</td><td align='center' style='background-color:grey'><img src='../images/scdlogodoorzichtig.gif' height='16' ></td><td align='center'>0</td><td align='center'>1</td><td align='center'>1</td><td align='center'>3</td></tr>
<tr><td align='center'>6</td><td align='left'>Apon, H.  (Iwahn)                       </td><td align='center'>0</td><td align='center'>0</td><td align='center'>0</td><td align='center'>1</td><td align='center'>1</td><td align='center' style='background-color:grey'><img src='../images/scdlogodoorzichtig.gif' height='16' ></td><td align='center'>0</td><td align='center'>0,5</td><td align='center'>2,5</td></tr>
<tr><td align='center'>7</td><td align='left'>Oliemans, C.  (Cor)                     </td><td align='center'>0</td><td align='center'>0</td><td align='center'>0,5</td><td align='center'>0</td><td align='center'>0</td><td align='center'>1</td><td align='center' style='background-color:grey'><img src='../images/scdlogodoorzichtig.gif' height='16' ></td><td align='center'>0,5</td><td align='center'>2</td></tr>
<tr><td align='center'>8</td><td align='left'>Hennekes, J.  (Jacques)                 </td><td align='center'>0</td><td align='center'>0,5</td><td align='center'>0</td><td align='center'>0</td><td align='center'>0</td><td align='center'>0,5</td><td align='center'>0,5</td><td align='center' style='background-color:grey'><img src='../images/scdlogodoorzichtig.gif' height='16' ></td><td align='center'>1,5</td></tr>
</table>
</div>
<br />
<br />
<input id="buttonprint" type="button" value="Prepare printing" onclick="PrintElem();">\
