document.write("\
<div id='printable' class='PrintSettings'>\
<h1 align=left>Schaakclub Dordrecht, Totaal stand kampioensgroep</h1>\
<br><table border='1px'>
<tr><td width='4%' align='center'>&nbsp;</td><td width='30%' align='left'>Naam</td><td width='4%' align='center'>1</td><td width='4%' align='center'>2</td><td width='4%' align='center'>3</td><td width='4%' align='center'>4</td><td width='4%' align='center'>5</td><td width='4%' align='center'>6</td><td width='4%' align='center'>7</td><td width='4%' align='center'>8</td><td width='4%' align='center'>Total</td>
<tr><td align='center'>1</td><td align='left' width='4%' >Boer, L. den (Lennard)</td><td align='center' style='background-color:grey'><img src='../images\scdlogodoorzichtig.gif' height='16' ></td><td align='center'>.</td><td align='center'>.</td><td align='center'>.</td><td align='center'>.</td><td align='center'>1</td><td align='center'>1</td><td align='center'>.</td><td align='center'>2</td></tr>
<tr><td align='center'>&nbsp;</td><td align='left' width='4%' >Timmermans, M.A.  (Mark)</td><td align='center'>.</td><td align='center' style='background-color:grey'><img src='../images\scdlogodoorzichtig.gif' height='16' ></td><td align='center'>.</td><td align='center'>.</td><td align='center'>1</td><td align='center'>.</td><td align='center'>.</td><td align='center'>1</td><td align='center'>2</td></tr>
<tr><td align='center'>3</td><td align='left' width='4%' >Wilde, R. de (Rik)</td><td align='center'>.</td><td align='center'>.</td><td align='center' style='background-color:grey'><img src='../images\scdlogodoorzichtig.gif' height='16' ></td><td align='center'>1</td><td align='center'>0,5</td><td align='center'>.</td><td align='center'>.</td><td align='center'>.</td><td align='center'>1,5</td></tr>
<tr><td align='center'>4</td><td align='left' width='4%' >Jong, J. de (Joop)</td><td align='center'>.</td><td align='center'>.</td><td align='center'>0</td><td align='center' style='background-color:grey'><img src='../images\scdlogodoorzichtig.gif' height='16' ></td><td align='center'>.</td><td align='center'>.</td><td align='center'>1</td><td align='center'>.</td><td align='center'>1</td></tr>
<tr><td align='center'>5</td><td align='left' width='4%' >Krul, R.  (Rene)</td><td align='center'>.</td><td align='center'>0</td><td align='center'>0,5</td><td align='center'>.</td><td align='center' style='background-color:grey'><img src='../images\scdlogodoorzichtig.gif' height='16' ></td><td align='center'>.</td><td align='center'>.</td><td align='center'>.</td><td align='center'>0,5</td></tr>
<tr><td align='center'>6</td><td align='left' width='4%' >Doorn, X. van (Xander)</td><td align='center'>0</td><td align='center'>.</td><td align='center'>.</td><td align='center'>.</td><td align='center'>.</td><td align='center' style='background-color:grey'><img src='../images\scdlogodoorzichtig.gif' height='16' ></td><td align='center'>.</td><td align='center'>.</td><td align='center'>0</td></tr>
<tr><td align='center'>&nbsp;</td><td align='left' width='4%' >Hennekes, J.  (Jacques)</td><td align='center'>0</td><td align='center'>.</td><td align='center'>.</td><td align='center'>0</td><td align='center'>.</td><td align='center'>.</td><td align='center' style='background-color:grey'><img src='../images\scdlogodoorzichtig.gif' height='16' ></td><td align='center'>.</td><td align='center'>0</td></tr>
<tr><td align='center'>&nbsp;</td><td align='left' width='4%' >Vogelesang, S.  (Sander)</td><td align='center'>.</td><td align='center'>0</td><td align='center'>.</td><td align='center'>.</td><td align='center'>.</td><td align='center'>.</td><td align='center'>.</td><td align='center' style='background-color:grey'><img src='../images\scdlogodoorzichtig.gif' height='16' ></td><td align='center'>0</td></tr>
</table>\
<br />\
<br />\
