<h1 align=left>Schaakclub Dordrecht, Voorjaarscompetitie 2016</h1>\
<h2 align=left>Out of Competition</h2>\
<br><table border='0'><tr><td width='4%' align='right'>Nr</td><td width='8%' align='center'>&nbsp;</td><td width='40%' align='left'><h2>Name</h2></td><td width='6%' align='right'>CP</td><td width='6%' align='right'>Points</td><td width='6%' align='right'>Games</td><td width='6%' align='right'>%</td><td width='22%' align='right'>&nbsp;</td></tr><tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='40%' align='left'>Linden, L. van der (Lukas) </h2></td><td width='6%' align='right'>2161,2</td><td width='6%' align='right'>1,5</td><td width='6%' align='right'>3</td><td width='6%' align='right'>50,0</td><td width='22%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='40%' align='left'>Krul, R.  (Rene) </h2></td><td width='6%' align='right'>2096,1</td><td width='6%' align='right'>1,0</td><td width='6%' align='right'>3</td><td width='6%' align='right'>33,3</td><td width='22%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='40%' align='left'>Dekker, W. den (Wijnand) </h2></td><td width='6%' align='right'>1969,6</td><td width='6%' align='right'>1,0</td><td width='6%' align='right'>2</td><td width='6%' align='right'>50,0</td><td width='22%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='40%' align='left'>Timmermans, A.L.  (Adri) </h2></td><td width='6%' align='right'>1875,2</td><td width='6%' align='right'>1,0</td><td width='6%' align='right'>4</td><td width='6%' align='right'>25,0</td><td width='22%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='40%' align='left'>Slagboom, T.  (Ton) </h2></td><td width='6%' align='right'>1840,7</td><td width='6%' align='right'>0,0</td><td width='6%' align='right'>1</td><td width='6%' align='right'>0,0</td><td width='22%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='40%' align='left'>Oliemans, C.  (Cor) </h2></td><td width='6%' align='right'>1826,6</td><td width='6%' align='right'>2,0</td><td width='6%' align='right'>4</td><td width='6%' align='right'>50,0</td><td width='22%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='40%' align='left'>Bonninga, A.  (Anko) </h2></td><td width='6%' align='right'>1490,5</td><td width='6%' align='right'>1,0</td><td width='6%' align='right'>2</td><td width='6%' align='right'>50,0</td><td width='22%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='40%' align='left'>Pulles, M.  (Mari) </h2></td><td width='6%' align='right'>1283,8</td><td width='6%' align='right'>0,0</td><td width='6%' align='right'>2</td><td width='6%' align='right'>0,0</td><td width='22%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='40%' align='left'>Doeselaar, J. van (Joas) </h2></td><td width='6%' align='right'>1202,5</td><td width='6%' align='right'>0,5</td><td width='6%' align='right'>1</td><td width='6%' align='right'>50,0</td><td width='22%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='40%' align='left'>Wu, J.  (Joy) </h2></td><td width='6%' align='right'>1143,1</td><td width='6%' align='right'>1,0</td><td width='6%' align='right'>3</td><td width='6%' align='right'>33,3</td><td width='22%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='40%' align='left'>Laars, P. van der (Peter) </h2></td><td width='6%' align='right'>1077,9</td><td width='6%' align='right'>2,0</td><td width='6%' align='right'>3</td><td width='6%' align='right'>66,7</td><td width='22%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='40%' align='left'>Hertog, J.A.P. den (Johan) </h2></td><td width='6%' align='right'>1030,6</td><td width='6%' align='right'>1,0</td><td width='6%' align='right'>2</td><td width='6%' align='right'>50,0</td><td width='22%' align='right'>&nbsp;</td></tr>\
</table>\
</div>\
<br />\
<br />\
");
