<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Timmermans, M.A.  (Mark) </td><td width='4%' align='right'>2331,0</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Wilde, R. de (Rik) </td><td width='4%' align='right'>2088,8</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Keeken, R. van (Roland) </td><td width='4%' align='right'>1882,0</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Doorn, X. van (Xander) </td><td width='4%' align='right'>1865,0</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Oevelen, P. van (Peter) </td><td width='4%' align='right'>1844,6</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Oliemans, C.  (Cor) </td><td width='4%' align='right'>1839,0</td><td width='4%' align='right'>1,0</td><td width='4%' align='right'>3</td><td width='4%' align='right'>33,3</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Apon, H.  (Iwahn) </td><td width='4%' align='right'>1820,8</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Slagboom, T.  (Ton) </td><td width='4%' align='right'>1784,0</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Vos, M.  (Martijn) </td><td width='4%' align='right'>1767,0</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Berrevoets, H.  (Hans) </td><td width='4%' align='right'>1756,3</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Timmermans, H.J.  (Henk) </td><td width='4%' align='right'>1754,8</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Wilde-Schakel, L. de (Lemmy) </td><td width='4%' align='right'>1754,5</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Timmermans, A.L.  (Adri) </td><td width='4%' align='right'>1734,8</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'>1</td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Rijneveen, M.  (Martijn) </td><td width='4%' align='right'>1704,5</td><td width='4%' align='right'>1,5</td><td width='4%' align='right'>2</td><td width='4%' align='right'>75,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Jongeneel, W.  (Wim) </td><td width='4%' align='right'>1650,3</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Schot, P.  (Peter) </td><td width='4%' align='right'>1564,0</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Weert, G. van der (Gerben) </td><td width='4%' align='right'>1562,0</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Wingerden, E. van (Erwin) </td><td width='4%' align='right'>1548,0</td><td width='4%' align='right'>1,0</td><td width='4%' align='right'>1</td><td width='4%' align='right'>100,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Hoek, T. van (Thijs) </td><td width='4%' align='right'>1538,5</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Haren, O.C. van (Otto) </td><td width='4%' align='right'>1424,9</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'>1</td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Bonninga, A.  (Anko) </td><td width='4%' align='right'>1361,2</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Barends, H.  (Henk) </td><td width='4%' align='right'>1306,2</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Herk, R. van (Robert) </td><td width='4%' align='right'>1172,0</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Vossen, C.  (Cor) </td><td width='4%' align='right'>1071,2</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Mulder, R  (Rien) </td><td width='4%' align='right'>1041,1</td><td width='4%' align='right'>0,0</td><td width='4%' align='right'></td><td width='4%' align='right'>0,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
<tr><td width='4%' align='right'>*</td><td width='8%' align='center'>&nbsp</td><td width='30%' align='left'>Visser, B.  (Bastiaan) </td><td width='4%' align='right'>969,9</td><td width='4%' align='right'>1,0</td><td width='4%' align='right'>1</td><td width='4%' align='right'>100,0</td><td width='42%' align='right'>&nbsp;</td></tr>\
</table>\
</div>\
<br />\
<br />\
<input id="buttonprint" type="button" value="Voorbereiding printen" onclick="PrintElem();">\
");
