document.write("\
<h1 align=left>Overview generated</h1>\
<h2 align=left>Schaakclub Dordrecht, Kroongroep 2016-2017</h2>\
<br>\
<table border='1'>\
<tr><td width='2%' align='right'>&nbsp;</td><td width='2%' align='right'>&nbsp;</td><td width='15%' align='left'>&nbsp;</td><td width='2%' align='right'>1</td><td width='2%' align='right'>2</td><td width='2%' align='right'>3</td><td width='2%' align='right'>4</td><td width='2%' align='right'>5</td><td width='2%' align='right'>6</td><td width='2%' align='right'>7</td><td width='2%' align='right'>8</td><td width='2%' align='right'>9</td><td width='2%' align='right'>10</td><td width='2%' align='right'>11</td><td width='2%' align='right'>12</td><td width='2%' align='right'>Total</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<td width='2%' align='right'>1</td><td width='2%' align='right'>1</td><td width='15%' align='left'>Abee, K.  (Koos )</td><td width='2%' align='right'>&nbsp;</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>0,0</td><td width='2%' align='center'>.</td><td width='2%' align='right'>0,0</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>0,0</td><td width='2%' align='right'>0,0</td><td width='2%' align='center'>.</td><td width='2%' align='right'>0,0</td><td width='2%' align='right'>0,0</td></tr>\
<td width='2%' align='right'>2</td><td width='2%' align='right'>11</td><td width='15%' align='left'>Apon, H.  (Iwahn )</td><td width='2%' align='center'>.</td><td width='2%' align='right'>&nbsp;</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>0,0</td></tr>\
<td width='2%' align='right'>3</td><td width='2%' align='right'>7</td><td width='15%' align='left'>Berrevoets, H.  (Hans )</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>&nbsp;</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>0,0</td></tr>\
<td width='2%' align='right'>4</td><td width='2%' align='right'>2</td><td width='15%' align='left'>Boer, L. den (Lennard )</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>&nbsp;</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>0,0</td></tr>\
<td width='2%' align='right'>5</td><td width='2%' align='right'>9</td><td width='15%' align='left'>Eikelboom, B.  (Berend )</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>&nbsp;</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>0,0</td></tr>\
<td width='2%' align='right'>6</td><td width='2%' align='right'>6</td><td width='15%' align='left'>Hennekes, J.  (Jacques )</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>&nbsp;</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>0,0</td></tr>\
<td width='2%' align='right'>7</td><td width='2%' align='right'>5</td><td width='15%' align='left'>Jong, J. de (Joop )</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>&nbsp;</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>0,0</td></tr>\
<td width='2%' align='right'>8</td><td width='2%' align='right'>3</td><td width='15%' align='left'>Oliemans, C.  (Cor )</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>&nbsp;</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>0,0</td></tr>\
<td width='2%' align='right'>9</td><td width='2%' align='right'>10</td><td width='15%' align='left'>Pluymert, P.W.  (Piet )</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>&nbsp;</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>0,0</td></tr>\
<td width='2%' align='right'>10</td><td width='2%' align='right'>4</td><td width='15%' align='left'>Timmermans, A.L.  (Adri )</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>&nbsp;</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>0,0</td></tr>\
<td width='2%' align='right'>11</td><td width='2%' align='right'>12</td><td width='15%' align='left'>Timmermans, M.A.  (Mark )</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>&nbsp;</td><td width='2%' align='center'>.</td><td width='2%' align='right'>0,0</td></tr>\
<td width='2%' align='right'>12</td><td width='2%' align='right'>8</td><td width='15%' align='left'>Wilde, R. de (Rik )</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='center'>.</td><td width='2%' align='right'>&nbsp;</td><td width='2%' align='right'>0,0</td></tr>\
</table>\
<br />\
<br />\
");
