document.write("\
<div id='printable'>\
<h1 align=left>Schaakclub Dordrecht, Schema Kroongroep</h1>\
<h2 align=left>--</h2>\
<br>\
<table border='0'>\
<tr><td width='4%' align='center'>Ronde</td><td width='4%' align='center'>Partij nr</td><td width='40%' align='left'>Wit</td><td width='40%' align='left'>Zwart</td><td width='10%' align='center'>Status</td></tr>\
<tr><td height='8'>&nbsp;<br></td></tr>\
<tr><td width='4%' align='center'>1</td><td width='4%' align='center'>1</td><td width='40%' align='left'>Abee, K.  (Koos )</td><td width='40%' align='left'>Timmermans, M.A.  (Mark )</td><td width='10%' align='center'>OK</td></tr>\
<tr><td width='4%' align='center'>1</td><td width='4%' align='center'>2</td><td width='40%' align='left'>Boer, L. den (Lennard )</td><td width='40%' align='left'>Apon, H.  (Iwahn )</td><td width='10%' align='center'>OK</td></tr>\
<tr><td width='4%' align='center'>1</td><td width='4%' align='center'>3</td><td width='40%' align='left'>Oliemans, C.  (Cor )</td><td width='40%' align='left'>Pluymert, P.W.  (Piet )</td><td width='10%' align='center'>OK</td></tr>\
<tr><td width='4%' align='center'>1</td><td width='4%' align='center'>4</td><td width='40%' align='left'>Timmermans, A.L.  (Adri )</td><td width='40%' align='left'>Eikelboom, B.  (Berend )</td><td width='10%' align='center'>OK</td></tr>\
<tr><td width='4%' align='center'>1</td><td width='4%' align='center'>5</td><td width='40%' align='left'>Jong, J. de (Joop )</td><td width='40%' align='left'>Wilde, R. de (Rik )</td><td width='10%' align='center'>OK</td></tr>\
<tr><td width='4%' align='center'>1</td><td width='4%' align='center'>6</td><td width='40%' align='left'>Hennekes, J.  (Jacques )</td><td width='40%' align='left'>Berrevoets, H.  (Hans )</td><td width='10%' align='center'>OK</td></tr>\
<tr><td width='4%' align='center'>2</td><td width='4%' align='center'>7</td><td width='40%' align='left'>Boer, L. den (Lennard )</td><td width='40%' align='left'>Abee, K.  (Koos )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>2</td><td width='4%' align='center'>8</td><td width='40%' align='left'>Timmermans, M.A.  (Mark )</td><td width='40%' align='left'>Oliemans, C.  (Cor )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>2</td><td width='4%' align='center'>9</td><td width='40%' align='left'>Apon, H.  (Iwahn )</td><td width='40%' align='left'>Timmermans, A.L.  (Adri )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>2</td><td width='4%' align='center'>10</td><td width='40%' align='left'>Pluymert, P.W.  (Piet )</td><td width='40%' align='left'>Jong, J. de (Joop )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>2</td><td width='4%' align='center'>11</td><td width='40%' align='left'>Eikelboom, B.  (Berend )</td><td width='40%' align='left'>Hennekes, J.  (Jacques )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>2</td><td width='4%' align='center'>12</td><td width='40%' align='left'>Wilde, R. de (Rik )</td><td width='40%' align='left'>Berrevoets, H.  (Hans )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>3</td><td width='4%' align='center'>13</td><td width='40%' align='left'>Abee, K.  (Koos )</td><td width='40%' align='left'>Oliemans, C.  (Cor )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>3</td><td width='4%' align='center'>14</td><td width='40%' align='left'>Timmermans, A.L.  (Adri )</td><td width='40%' align='left'>Boer, L. den (Lennard )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>3</td><td width='4%' align='center'>15</td><td width='40%' align='left'>Jong, J. de (Joop )</td><td width='40%' align='left'>Timmermans, M.A.  (Mark )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>3</td><td width='4%' align='center'>16</td><td width='40%' align='left'>Hennekes, J.  (Jacques )</td><td width='40%' align='left'>Apon, H.  (Iwahn )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>3</td><td width='4%' align='center'>17</td><td width='40%' align='left'>Berrevoets, H.  (Hans )</td><td width='40%' align='left'>Pluymert, P.W.  (Piet )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>3</td><td width='4%' align='center'>18</td><td width='40%' align='left'>Wilde, R. de (Rik )</td><td width='40%' align='left'>Eikelboom, B.  (Berend )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>4</td><td width='4%' align='center'>19</td><td width='40%' align='left'>Timmermans, A.L.  (Adri )</td><td width='40%' align='left'>Abee, K.  (Koos )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>4</td><td width='4%' align='center'>20</td><td width='40%' align='left'>Oliemans, C.  (Cor )</td><td width='40%' align='left'>Jong, J. de (Joop )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>4</td><td width='4%' align='center'>21</td><td width='40%' align='left'>Boer, L. den (Lennard )</td><td width='40%' align='left'>Hennekes, J.  (Jacques )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>4</td><td width='4%' align='center'>22</td><td width='40%' align='left'>Timmermans, M.A.  (Mark )</td><td width='40%' align='left'>Berrevoets, H.  (Hans )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>4</td><td width='4%' align='center'>23</td><td width='40%' align='left'>Apon, H.  (Iwahn )</td><td width='40%' align='left'>Wilde, R. de (Rik )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>4</td><td width='4%' align='center'>24</td><td width='40%' align='left'>Pluymert, P.W.  (Piet )</td><td width='40%' align='left'>Eikelboom, B.  (Berend )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>5</td><td width='4%' align='center'>25</td><td width='40%' align='left'>Abee, K.  (Koos )</td><td width='40%' align='left'>Jong, J. de (Joop )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>5</td><td width='4%' align='center'>26</td><td width='40%' align='left'>Hennekes, J.  (Jacques )</td><td width='40%' align='left'>Timmermans, A.L.  (Adri )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>5</td><td width='4%' align='center'>27</td><td width='40%' align='left'>Berrevoets, H.  (Hans )</td><td width='40%' align='left'>Oliemans, C.  (Cor )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>5</td><td width='4%' align='center'>28</td><td width='40%' align='left'>Wilde, R. de (Rik )</td><td width='40%' align='left'>Boer, L. den (Lennard )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>5</td><td width='4%' align='center'>29</td><td width='40%' align='left'>Eikelboom, B.  (Berend )</td><td width='40%' align='left'>Timmermans, M.A.  (Mark )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>5</td><td width='4%' align='center'>30</td><td width='40%' align='left'>Pluymert, P.W.  (Piet )</td><td width='40%' align='left'>Apon, H.  (Iwahn )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>6</td><td width='4%' align='center'>31</td><td width='40%' align='left'>Hennekes, J.  (Jacques )</td><td width='40%' align='left'>Abee, K.  (Koos )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>6</td><td width='4%' align='center'>32</td><td width='40%' align='left'>Jong, J. de (Joop )</td><td width='40%' align='left'>Berrevoets, H.  (Hans )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>6</td><td width='4%' align='center'>33</td><td width='40%' align='left'>Timmermans, A.L.  (Adri )</td><td width='40%' align='left'>Wilde, R. de (Rik )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>6</td><td width='4%' align='center'>34</td><td width='40%' align='left'>Oliemans, C.  (Cor )</td><td width='40%' align='left'>Eikelboom, B.  (Berend )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>6</td><td width='4%' align='center'>35</td><td width='40%' align='left'>Boer, L. den (Lennard )</td><td width='40%' align='left'>Pluymert, P.W.  (Piet )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>6</td><td width='4%' align='center'>36</td><td width='40%' align='left'>Timmermans, M.A.  (Mark )</td><td width='40%' align='left'>Apon, H.  (Iwahn )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>7</td><td width='4%' align='center'>37</td><td width='40%' align='left'>Abee, K.  (Koos )</td><td width='40%' align='left'>Berrevoets, H.  (Hans )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>7</td><td width='4%' align='center'>38</td><td width='40%' align='left'>Wilde, R. de (Rik )</td><td width='40%' align='left'>Hennekes, J.  (Jacques )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>7</td><td width='4%' align='center'>39</td><td width='40%' align='left'>Eikelboom, B.  (Berend )</td><td width='40%' align='left'>Jong, J. de (Joop )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>7</td><td width='4%' align='center'>40</td><td width='40%' align='left'>Pluymert, P.W.  (Piet )</td><td width='40%' align='left'>Timmermans, A.L.  (Adri )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>7</td><td width='4%' align='center'>41</td><td width='40%' align='left'>Apon, H.  (Iwahn )</td><td width='40%' align='left'>Oliemans, C.  (Cor )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>7</td><td width='4%' align='center'>42</td><td width='40%' align='left'>Timmermans, M.A.  (Mark )</td><td width='40%' align='left'>Boer, L. den (Lennard )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>8</td><td width='4%' align='center'>43</td><td width='40%' align='left'>Wilde, R. de (Rik )</td><td width='40%' align='left'>Abee, K.  (Koos )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>8</td><td width='4%' align='center'>44</td><td width='40%' align='left'>Berrevoets, H.  (Hans )</td><td width='40%' align='left'>Eikelboom, B.  (Berend )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>8</td><td width='4%' align='center'>45</td><td width='40%' align='left'>Hennekes, J.  (Jacques )</td><td width='40%' align='left'>Pluymert, P.W.  (Piet )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>8</td><td width='4%' align='center'>46</td><td width='40%' align='left'>Jong, J. de (Joop )</td><td width='40%' align='left'>Apon, H.  (Iwahn )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>8</td><td width='4%' align='center'>47</td><td width='40%' align='left'>Timmermans, A.L.  (Adri )</td><td width='40%' align='left'>Timmermans, M.A.  (Mark )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>8</td><td width='4%' align='center'>48</td><td width='40%' align='left'>Oliemans, C.  (Cor )</td><td width='40%' align='left'>Boer, L. den (Lennard )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>9</td><td width='4%' align='center'>49</td><td width='40%' align='left'>Abee, K.  (Koos )</td><td width='40%' align='left'>Eikelboom, B.  (Berend )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>9</td><td width='4%' align='center'>50</td><td width='40%' align='left'>Pluymert, P.W.  (Piet )</td><td width='40%' align='left'>Wilde, R. de (Rik )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>9</td><td width='4%' align='center'>51</td><td width='40%' align='left'>Apon, H.  (Iwahn )</td><td width='40%' align='left'>Berrevoets, H.  (Hans )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>9</td><td width='4%' align='center'>52</td><td width='40%' align='left'>Timmermans, M.A.  (Mark )</td><td width='40%' align='left'>Hennekes, J.  (Jacques )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>9</td><td width='4%' align='center'>53</td><td width='40%' align='left'>Boer, L. den (Lennard )</td><td width='40%' align='left'>Jong, J. de (Joop )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>9</td><td width='4%' align='center'>54</td><td width='40%' align='left'>Oliemans, C.  (Cor )</td><td width='40%' align='left'>Timmermans, A.L.  (Adri )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>10</td><td width='4%' align='center'>55</td><td width='40%' align='left'>Pluymert, P.W.  (Piet )</td><td width='40%' align='left'>Abee, K.  (Koos )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>10</td><td width='4%' align='center'>56</td><td width='40%' align='left'>Eikelboom, B.  (Berend )</td><td width='40%' align='left'>Apon, H.  (Iwahn )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>10</td><td width='4%' align='center'>57</td><td width='40%' align='left'>Wilde, R. de (Rik )</td><td width='40%' align='left'>Timmermans, M.A.  (Mark )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>10</td><td width='4%' align='center'>58</td><td width='40%' align='left'>Berrevoets, H.  (Hans )</td><td width='40%' align='left'>Boer, L. den (Lennard )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>10</td><td width='4%' align='center'>59</td><td width='40%' align='left'>Hennekes, J.  (Jacques )</td><td width='40%' align='left'>Oliemans, C.  (Cor )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>10</td><td width='4%' align='center'>60</td><td width='40%' align='left'>Jong, J. de (Joop )</td><td width='40%' align='left'>Timmermans, A.L.  (Adri )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>11</td><td width='4%' align='center'>61</td><td width='40%' align='left'>Abee, K.  (Koos )</td><td width='40%' align='left'>Apon, H.  (Iwahn )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>11</td><td width='4%' align='center'>62</td><td width='40%' align='left'>Timmermans, M.A.  (Mark )</td><td width='40%' align='left'>Pluymert, P.W.  (Piet )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>11</td><td width='4%' align='center'>63</td><td width='40%' align='left'>Boer, L. den (Lennard )</td><td width='40%' align='left'>Eikelboom, B.  (Berend )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>11</td><td width='4%' align='center'>64</td><td width='40%' align='left'>Oliemans, C.  (Cor )</td><td width='40%' align='left'>Wilde, R. de (Rik )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>11</td><td width='4%' align='center'>65</td><td width='40%' align='left'>Timmermans, A.L.  (Adri )</td><td width='40%' align='left'>Berrevoets, H.  (Hans )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
<tr><td width='4%' align='center'>11</td><td width='4%' align='center'>66</td><td width='40%' align='left'>Jong, J. de (Joop )</td><td width='40%' align='left'>Hennekes, J.  (Jacques )</td><td width='10%' align='center'>Nog geen resultaat</td></tr>\
</table>\
</div>\
<br />\
<br />\
");
