document.write("\
<div id='printable'>\
<h1 align=left>Schaakclub Dordrecht, Kroongroep overzicht</h1>\
<br><table border='1px' cellpadding='10'>
<tr><td align='center'>&nbsp;</td><td align='left'>Name</td><td align='center'>1</td><td align='center'>2</td><td align='center'>3</td><td align='center'>4</td><td align='center'>5</td><td align='center'>6</td><td align='center'>7</td><td align='center'>8</td><td align='center'>9</td><td align='center'>10</td><td align='center'>11</td><td align='center'>12</td><td align='center'>Total</td>
<tr><td align='center'>1</td><td align='left'>Timmermans, M.A.  (Mark)                </td><td align='center' style='background-color:grey'>&nbsp;</td><td align='center'>.</td><td align='center'>1</td><td align='center'>0,5</td><td align='center'>1</td><td align='center'>1</td><td align='center'>1</td><td align='center'>1</td><td align='center'>1</td><td align='center'>1</td><td align='center'>1</td><td align='center'>1</td><td align='center'>9,5</td></tr>
<tr><td align='center'>2</td><td align='left'>Krul, R.  (Rene)                        </td><td align='center'>.</td><td align='center' style='background-color:grey'>&nbsp;</td><td align='center'>1</td><td align='center'>0</td><td align='center'>.</td><td align='center'>1</td><td align='center'>.</td><td align='center'>0,5</td><td align='center'>0,5</td><td align='center'>1</td><td align='center'>1</td><td align='center'>1</td><td align='center'>6</td></tr>
<tr><td align='center'>&nbsp;</td><td align='left'>Jong, J. de (Joop)                      </td><td align='center'>0</td><td align='center'>0</td><td align='center' style='background-color:grey'>&nbsp;</td><td align='center'>0,5</td><td align='center'>0,5</td><td align='center'>0,5</td><td align='center'>0,5</td><td align='center'>1</td><td align='center'>1</td><td align='center'>0,5</td><td align='center'>0,5</td><td align='center'>1</td><td align='center'>6</td></tr>
<tr><td align='center'>&nbsp;</td><td align='left'>Wilde, R. de (Rik)                      </td><td align='center'>0,5</td><td align='center'>1</td><td align='center'>0,5</td><td align='center' style='background-color:grey'>&nbsp;</td><td align='center'>0,5</td><td align='center'>0,5</td><td align='center'>.</td><td align='center'>1</td><td align='center'>0</td><td align='center'>.</td><td align='center'>1</td><td align='center'>1</td><td align='center'>6</td></tr>
<tr><td align='center'>5</td><td align='left'>Boer, L. den (Lennard)                  </td><td align='center'>0</td><td align='center'>.</td><td align='center'>0,5</td><td align='center'>0,5</td><td align='center' style='background-color:grey'>&nbsp;</td><td align='center'>1</td><td align='center'>.</td><td align='center'>0,5</td><td align='center'>0,5</td><td align='center'>0</td><td align='center'>1</td><td align='center'>1</td><td align='center'>5</td></tr>
<tr><td align='center'>6</td><td align='left'>Hennekes, J.  (Jacques)                 </td><td align='center'>0</td><td align='center'>0</td><td align='center'>0,5</td><td align='center'>0,5</td><td align='center'>0</td><td align='center' style='background-color:grey'>&nbsp;</td><td align='center'>0,5</td><td align='center'>0</td><td align='center'>.</td><td align='center'>1</td><td align='center'>1</td><td align='center'>1</td><td align='center'>4,5</td></tr>
<tr><td align='center'>&nbsp;</td><td align='left'>Keeken, R. Van (Roland)                 </td><td align='center'>0</td><td align='center'>.</td><td align='center'>0,5</td><td align='center'>.</td><td align='center'>.</td><td align='center'>0,5</td><td align='center' style='background-color:grey'>&nbsp;</td><td align='center'>.</td><td align='center'>1</td><td align='center'>1</td><td align='center'>0,5</td><td align='center'>1</td><td align='center'>4,5</td></tr>
<tr><td align='center'>&nbsp;</td><td align='left'>Oevelen, P. Van (Peter)                 </td><td align='center'>0</td><td align='center'>0,5</td><td align='center'>0</td><td align='center'>0</td><td align='center'>0,5</td><td align='center'>1</td><td align='center'>.</td><td align='center' style='background-color:grey'>&nbsp;</td><td align='center'>0</td><td align='center'>0,5</td><td align='center'>1</td><td align='center'>1</td><td align='center'>4,5</td></tr>
<tr><td align='center'>9</td><td align='left'>Koppelaar, V.  (Victor)                 </td><td align='center'>0</td><td align='center'>0,5</td><td align='center'>0</td><td align='center'>1</td><td align='center'>0,5</td><td align='center'>.</td><td align='center'>0</td><td align='center'>1</td><td align='center' style='background-color:grey'>&nbsp;</td><td align='center'>0</td><td align='center'>.</td><td align='center'>1</td><td align='center'>4</td></tr>
<tr><td align='center'>&nbsp;</td><td align='left'>Apon, H.  (Iwahn)                       </td><td align='center'>0</td><td align='center'>0</td><td align='center'>0,5</td><td align='center'>.</td><td align='center'>1</td><td align='center'>0</td><td align='center'>0</td><td align='center'>0,5</td><td align='center'>1</td><td align='center' style='background-color:grey'>&nbsp;</td><td align='center'>0</td><td align='center'>1</td><td align='center'>4</td></tr>
<tr><td align='center'>11</td><td align='left'>Timmermans, A.L.  (Adri)                </td><td align='center'>0</td><td align='center'>0</td><td align='center'>0,5</td><td align='center'>0</td><td align='center'>0</td><td align='center'>0</td><td align='center'>0,5</td><td align='center'>0</td><td align='center'>.</td><td align='center'>1</td><td align='center' style='background-color:grey'>&nbsp;</td><td align='center'>1</td><td align='center'>3</td></tr>
<tr><td align='center'>12</td><td align='left'>Vogelesang, S  (Sander)                 </td><td align='center'>0</td><td align='center'>0</td><td align='center'>0</td><td align='center'>0</td><td align='center'>0</td><td align='center'>0</td><td align='center'>0</td><td align='center'>0</td><td align='center'>0</td><td align='center'>0</td><td align='center'>0</td><td align='center' style='background-color:grey'>&nbsp;</td><td align='center'>0</td></tr>
</table>
</div>
<br />
<br />
